# Generated by Django 4.2.5 on 2023-10-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateField()),
                ('iaa', models.FloatField(default=0)),
                ('ecpm', models.FloatField(default=0)),
                ('impression', models.IntegerField(default=0)),
                ('iap', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('cpi', models.FloatField(default=0)),
                ('install', models.FloatField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateField()),
                ('network', models.CharField(default='Applovin', max_length=255)),
                ('iaa', models.FloatField(default=0)),
                ('ecpm', models.FloatField(default=0)),
                ('impression', models.IntegerField(default=0)),
                ('iap', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('cpi', models.FloatField(default=0)),
                ('install', models.FloatField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
